name: Lint and Check TypeScript & Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint . --ext .ts --max-warnings=0
      - name: TypeScript type check
        run: npx tsc --noEmit
      - name: Playwright test dry run
        run: npx playwright test --list
