on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests (HTML reporter)
        # run: npx playwright test --reporter=html
        run: npx playwright test --project=chromium --grep @smoke

      - name: Show report contents (debug)
        if: always()
        run: |
          echo "Report folder listing:"
          ls -la playwright-report || true
          find playwright-report -type f -maxdepth 4 -print || true

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Configure Pages
        if: always()
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./playwright-report

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v1